<?php
require_once('./inc/verifylogin.inc.php');
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '    <meta charset="UTF-8">';
echo '    <meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '    <meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '    <title>Add Client</title>';
echo '</head>';
echo '<body>';
echo '    <a href="/">Back</a>';
echo '    <form action="processclient.php" method="post" style="border: 2px; width: 400px">';
echo '        <fieldset>';
echo '            <legend>Add Client</legend>';
echo '            <label for="fname"><strong>First Name:</strong></label><br>';
echo '            <input type="text" id="fname" name="fname"><br>';
echo '            <label for="lname"><strong>Last Name:</strong></label><br>';
echo '            <input type="text" id="lname" name="lname"><br>';
echo '            <label for="email"><strong>Email:</strong></label><br>';
echo '            <input type="email" id="email" name="email"><br>';
echo '            <label for="phone"><strong>Phone (In the format xxxxx xxxxxx):</strong></label><br>';
echo '            <input type="tel" id="phone" name="phone" pattern="[0-9]{5} [0-9]{6}"><br>';
echo '            <input type="submit" value="Save">';
echo '        </fieldset>';
echo '    </form>';
echo '</body>';
echo '</html>';
